### Numpy:
  * NumPy(Numerical Python): is python Library used for fast mathematical calculation,working with array,in ai and scienitific computing.
  

In [1]:
import numpy as np

In [2]:
# Numpy array
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


In [3]:
print('Type of Array',type(numpy_array))

Type of Array <class 'numpy.ndarray'>


In [4]:
print('Dimension of Array',numpy_array.ndim)

Dimension of Array 1


In [5]:
print ('Shape of Array',numpy_array.shape)

Shape of Array (5,)


In [6]:
print ('Size of Array',numpy_array.size)
print('DataType of Array',numpy_array.dtype)

Size of Array 5
DataType of Array int64


In [7]:
array_one=np.array([10,20,30,40])

In [11]:
print(array_one)

[10 20 30 40]


In [8]:
print('Dimension of Array',array_one.ndim)
print ('Shape of Array',array_one.shape)
print ('Size of Array',array_one.size)
print('DataType of Array',array_one.dtype)


Dimension of Array 1
Shape of Array (4,)
Size of Array 4
DataType of Array int64


In [10]:
array_two=np.array([[10,20],
                   [30,40]])

In [12]:
print(array_two)

[[10 20]
 [30 40]]


In [13]:
print('Dimension of Array',array_two.ndim)
print ('Shape of Array',array_two.shape)
print ('Size of Array',array_two.size)
print('DataType of Array',array_two.dtype)

Dimension of Array 2
Shape of Array (2, 2)
Size of Array 4
DataType of Array int64


In [20]:
array_3=np.array(
    [
        [[10,20,30],[30,40,50]],
        [[40,50,60],[60,79,90]],
         [[40,50,60],[60,79,90]]

     ]
)

In [21]:
print(array_3)

[[[10 20 30]
  [30 40 50]]

 [[40 50 60]
  [60 79 90]]

 [[40 50 60]
  [60 79 90]]]


In [22]:
print('Dimension of Array',array_3.ndim)
print ('Shape of Array',array_3.shape)
print ('Size of Array',array_3.size)
print('DataType of Array',array_3.dtype)

Dimension of Array 3
Shape of Array (3, 2, 3)
Size of Array 18
DataType of Array int64


In [23]:
# Numpy Special Arrays zeros, ones, range, eye, linspace
array_zeros=np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
print('Dimension of Array',array_zeros.ndim)
print ('Shape of Array',array_zeros.shape)
print ('Size of Array',array_zeros.size)
print('DataType of Array',array_zeros.dtype)

Dimension of Array 2
Shape of Array (3, 3)
Size of Array 9
DataType of Array float64


In [25]:
array_ones=np.ones((3,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
identiy_matrix=np.eye(3)
print(identiy_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
my_array=np.arange(1,100,1)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [31]:
line_space=np.linspace(1,100,10)
print(line_space)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [35]:
#Numpy Mathematical operations
array_one=np.array([10,20,30,5,2])

In [36]:
print('Sum of items: ',np.sum(array_one))


Sum of items:  67


In [37]:
print('Min of items',np.min(array_one))

Min of items 2


In [38]:
print('Max of items',np.max(array_one))

Max of items 30


In [39]:
print('Mean of items',np.mean(array_one))

Mean of items 13.4


In [41]:
print('Std of items',np.std(array_one))

Std of items 10.307278981380101


In [45]:
a_one=np.array([10,2,3,4,15])
a_two=np.array([5,12,16,48,5])
array_ab=np.concatenate((a_one,a_two))
print(array_ab)

[10  2  3  4 15  5 12 16 48  5]


In [47]:
a_one=np.array([10,2,3,4,15])
a_two=np.array([5,12,16,48,5])
a_three=np.array([1,2,3,4,5])
array_ab=np.concatenate((a_one,a_two,a_three))
print(array_ab)


[10  2  3  4 15  5 12 16 48  5  1  2  3  4  5]


In [48]:
#Numpy  Array split
array_split=np.array_split(array_ab,3)
print(array_split)

[array([10,  2,  3,  4, 15]), array([ 5, 12, 16, 48,  5]), array([1, 2, 3, 4, 5])]


In [49]:
sorted_array=np.sort(array_ab)
print(sorted_array)

[ 1  2  2  3  3  4  4  5  5  5 10 12 15 16 48]


In [50]:
# Create Array of All Items less than 10
array_less_than_10=array_ab[array_ab<10]
print(array_less_than_10)

[2 3 4 5 5 1 2 3 4 5]


In [51]:
# Create Array of All Items less than 10
array_not_5=array_ab[array_ab!=5]
print(array_not_5)

[10  2  3  4 15 12 16 48  1  2  3  4]


In [ ]:
#create a numPy Array for following numbers:10,12,13,45,68,69,70,89
#find out all numbers using filter

In [52]:
given_array=np.array([10,12,13,45,68,69,70,89])

In [53]:
print(given_array)

[10 12 13 45 68 69 70 89]


In [54]:
odd_numbers=given_array[given_array%2!=0]
print(odd_numbers)

[13 45 69 89]


In [55]:
even_numbers=given_array[given_array%2==0]
print(even_numbers)

[10 12 68 70]


In [56]:
student_marks=np.array([78,89,70,90,96,65,74])

In [57]:
print('Average marks: ',np.mean(student_marks))

Average marks:  80.28571428571429


In [58]:
print('Highest marks',np.max(student_marks))

Highest marks 96


In [59]:
print('Lowest Marks',np.min(student_marks))

Lowest Marks 65


In [60]:
print('Passed Students: ',student_marks[student_marks>=75])

Passed Students:  [78 89 90 96]
