In [1]:
import numpy as np

In [10]:
array1=np.array([15,20,30,14,55])
print(array1)

[15 20 30 14 55]


In [3]:
print('Typer of Array',type(array1))

Typer of Array <class 'numpy.ndarray'>


In [4]:
print('Dimension of Array',array1.ndim)

Dimension of Array 1


In [5]:
print('Shape of Array',array1.shape)

Shape of Array (5,)


In [6]:
print('Data Type of array',array1.dtype)

Data Type of array int64


In [7]:
print('All items in array or no of items',array1.size)

All items in array or no of items 5


In [11]:
for (i,item) in enumerate(array1):
  print(i,item)

0 15
1 20
2 30
3 14
4 55


In [12]:
print('Total of 3rd and 4th iteme',(array1[2]+array1[3]))

Total of 3rd and 4th iteme 44


**Creating 2D Array Using NumPy**

In [14]:
arr2=np.array([[10,20,30,],[44,55,66]])

In [16]:
print('arr2 Dimension',arr2.ndim)
print('arr2 shape',arr2.shape)
print('arr2 size',arr2.size)
print('arr2 type',arr2.dtype)


arr2 Dimension 2
arr2 shape (2, 3)
arr2 size 6
arr2 type int64


In [19]:
print('All items in arr2 as follows')
for item in arr2:
    print(item)

print('All items in arr3 as follows')

All items in arr2 as follows
[10 20 30]
[44 55 66]
All items in arr3 as follows


In [20]:
# Multidimensional index iterator.
# Return an iterator yielding pairs of array coordinates and values
for i,v in np.ndenumerate(arr2):
  print(f'{i}->{v}')

(0, 0)->10
(0, 1)->20
(0, 2)->30
(1, 0)->44
(1, 1)->55
(1, 2)->66


In [31]:
array_zeros=np.zeros((2,4))

In [32]:
print('array_zero_one Dimension',array_zeros.ndim)
print('array_zero_one Shape',array_zeros.shape)
print('array_zero_one size',array_zeros.size)
print('array_zero_one type',array_zeros.dtype)


array_zero_one Dimension 2
array_zero_one Shape (2, 4)
array_zero_one size 8
array_zero_one type float64


In [33]:
print('All items in array_zero_one as follows')
for item in array_zeros:
    print(item)

All items in array_zero_one as follows
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [34]:
for index,value in np.ndenumerate(array_zeros):
  print(f'{index}:{value}')

(0, 0):0.0
(0, 1):0.0
(0, 2):0.0
(0, 3):0.0
(1, 0):0.0
(1, 1):0.0
(1, 2):0.0
(1, 3):0.0


In [35]:
array_ones=np.ones((3,4))

In [37]:
print('array_ones Dimension',array_ones.ndim)
print('array_ones Shape',array_ones.shape)
print('array_ones size',array_ones.size)
print('array_ones type',array_ones.dtype)

array_ones Dimension 2
array_ones Shape (3, 4)
array_ones size 12
array_ones type float64


In [38]:
print('All item in array_ones as follows')
for item in array_ones:
  print(item)

All item in array_ones as follows
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]


In [39]:
for index,value in np.ndenumerate(array_ones):
  print(f'{index}:{value}')

(0, 0):1.0
(0, 1):1.0
(0, 2):1.0
(0, 3):1.0
(1, 0):1.0
(1, 1):1.0
(1, 2):1.0
(1, 3):1.0
(2, 0):1.0
(2, 1):1.0
(2, 2):1.0
(2, 3):1.0


In [41]:
#creating array with constant value
#Return a new array of given shape and type, filled with fill_value. e.g. 9
array_constant=np.full((3,4),9)

In [42]:
print('array_ones Dimension',array_constant.ndim)
print('array_ones Shape',array_constant.shape)
print('array_ones size',array_constant.size)
print('array_ones type',array_constant.dtype)

array_ones Dimension 2
array_ones Shape (3, 4)
array_ones size 12
array_ones type int64


In [44]:
print('All item in array_ones as follows')
for item in array_constant:
  print(item)

All item in array_ones as follows
[9 9 9 9]
[9 9 9 9]
[9 9 9 9]


In [45]:
for index,value in np.ndenumerate(array_constant):
  print(f'{index}:{value}')

(0, 0):9
(0, 1):9
(0, 2):9
(0, 3):9
(1, 0):9
(1, 1):9
(1, 2):9
(1, 3):9
(2, 0):9
(2, 1):9
(2, 2):9
(2, 3):9


In [52]:
array_random=np.random.rand(3,4)

In [53]:
print(' Dimension',array_random.ndim)
print(' Shape',array_random.shape)
print(' size',array_random.size)
print(' type',array_random.dtype)

 Dimension 2
 Shape (3, 4)
 size 12
 type float64


In [54]:
for index,value in np.ndenumerate(array_random):
  print(f'{index}:{value}')

(0, 0):0.6478681159855734
(0, 1):0.9759414753511599
(0, 2):0.25429520075114853
(0, 3):0.9622995059363307
(1, 0):0.47856649932354434
(1, 1):0.3275346017684496
(1, 2):0.07505850955293258
(1, 3):0.47340145064240113
(2, 0):0.6128912350205766
(2, 1):0.08436444500192475
(2, 2):0.24903954807640394
(2, 3):0.41377379626271515


In [60]:
from re import A
#NumPy Array Join
a_one=np.array([10,2,3,41])
a_two=np.array([5,16,17,8])
array_ab=np.concatenate((a_one,a_two))
print(array_ab)



[10  2  3 41  5 16 17  8]


In [61]:
#Numpy Array Split
array_split=np.array_split(array_ab,4)
print(array_split)

[array([10,  2]), array([ 3, 41]), array([ 5, 16]), array([17,  8])]


In [62]:
array_split3=np.array_split(array_ab,3)
print(array_split3)

[array([10,  2,  3]), array([41,  5, 16]), array([17,  8])]


In [63]:
#Sorting the NumpyArray
array_sort=np.sort(array_ab)
print(array_sort)

[ 2  3  5  8 10 16 17 41]


In [64]:
#Array of All items less than 20
array_less_than_20=array_ab[array_ab<20]
print(array_less_than_20)

[10  2  3  5 16 17  8]


In [65]:
array_not_10=array_ab[array_ab!=10]
print(array_not_10)

[ 2  3 41  5 16 17  8]


**Create a NumPy array for following Numbers **


*  10,12,13,45,67,89
* find out all odd numbers using filter like above

In [68]:
#Let us write of KL
temp_kl=np.array([35,35,28,35,27,29,34,33,25,32,28,26,25,25,24,24,25,30,24,26,32,25,23,32,25,24,28,24,25,30
])

In [69]:
print(' size',temp_kl.size)

 size 30


In [74]:
average_temp=temp_kl.mean()
print(f'Average temp of KL in last 30 days: {average_temp} °C')

Average temp of KL in last 30 days: 27.933333333333334 °C


In [75]:
print(f'Max temp of KL in last 30 days: {temp_kl.max()} °C')

Max temp of KL in last 30 days: 35 °C


In [76]:
print(f'Min temp of KL in last 30 days: {temp_kl.min()} °C')

Min temp of KL in last 30 days: 23 °C


In [86]:
hot_days=temp_kl[temp_kl>30]
print(f'Hot Days {len(hot_days)} are following')
for day in hot_days:
  print(f'{day}°C',end="\t ")
#

Hot Days 8 are following
35°C	 35°C	 35°C	 34°C	 33°C	 32°C	 32°C	 32°C	 

In [87]:
cool_days=temp_kl[temp_kl<25]
print(f'Cool Days  {len(cool_days)} are following')
for day in cool_days:
    print(f'{day}°C',end="\t ")
#

Cool Days  6 are following
24°C	 24°C	 24°C	 23°C	 24°C	 24°C	 

In [89]:
student_marks=np.array(
    [
        [78,80,86,90,85,91],
        [90,71,86,90,75,90],
        [98,88,80,90,83,88],
        [88,83,80,90,82,76],
        [67,89,81,90,71,73],
    ]

)
# * Here Each Row =One student
# *  Each Column =marks in subject
# *  we have six subjects and five students


#Exercise
1. Find out dimension,size, and datatype of array
2. Find out aver marks of each student
3. Find out highest marks  in each subject
4. Find out overall class average
5. Find out index(row,colum) of the lowest mark in entire array

In [ ]:
#Here Each Row =One student
# Each Column =marks in subject
# we have six subjects and five students
#Exercise


In [90]:
#Answer 1
print(' Dimension',student_marks.ndim)
print(' Shape',student_marks.shape)
print(' size',student_marks.size)
print(' type',student_marks.dtype)


 Dimension 2
 Shape (5, 6)
 size 30
 type int64


In [91]:
#Find out aver marks of each student
average_marks=student_marks.mean(axis=1)
print(average_marks)
#

[85.         83.66666667 87.83333333 83.16666667 78.5       ]


In [92]:
#Find out highest marks in each subject
highest_marks=student_marks.max(axis=0)
print(highest_marks)
#

[98 89 86 90 85 91]


In [93]:
#Find out overall class average
overall_class_average=student_marks.mean()
print(overall_class_average)
#

83.63333333333334


In [94]:
#Find out index(row,colum) of the lowest mark in entire array
total_marks=student_marks.sum(axis=1)
print(total_marks)
top_student_index=np.argmax(total_marks)
print(f'Top student index {top_student_index}')
#
#

[510 502 527 499 471]
Top student index 2
